# Nazwa klawiatury
CONFIG_ZMK_KEYBOARD_NAME="Zyra FT"

# BT - moc nadawcza
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep
CONFIG_ZMK_SLEEP=y

# ZMK Studio (shield cradio ma już feature 'studio' w upstream)
CONFIG_ZMK_STUDIO=y

# Eager debouncing (jak w innych klawiaturach FT)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
